DassHydro/smash

- doc/source/release/0.5.0-notes.rst
- doc/source/release/index.rst
- smash/core/simulation/_standardize.py
- Increase tolerance for bounds checking from 1e-6 to 1e-3
- Initialize new release note 0.5.0
> FIX: boudary conditions checking with higher tolerance

- doc/source/release/0.5.0-notes.rst
> FIX: Add new line before release note title

- doc/source/api_reference/hdf5_handler.rst
- doc/source/api_reference/hdf5_io.rst
- doc/source/api_reference/object_handler.rst
- doc/source/release/0.5.0-notes.rst
Fix missing files in api_reference for documentation
> ENC/FIX: Add highlights and contributors to release note

- doc/source/release/0.5.0-notes.rst
- smash/mesh/mw_meshing.f90
This commit fix an error when flow distances are computed on adjacent non-nested catchments
> FIX: resolve issue on flow distances computation

- smash/core/signal_analysis/segmentation/segmentation.py
- smash/core/signal_analysis/signatures/signatures.py
Check if df is empty before concatenating dataframes.
> FIX: fix deprecated warning of pandas 0.2.1 on signatures and segmentation computation

- doc/source/api_reference/principal_methods/simulation.rst
- doc/source/gen_rst.py
- smash/__init__.py
- smash/_constant.py
- smash/core/model/model.py
- smash/core/signal_analysis/prcp_indices/prcp_indices.py
- smash/core/signal_analysis/segmentation/segmentation.py
- smash/core/signal_analysis/signatures/signatures.py
- smash/core/simulation/_standardize.py
- smash/core/simulation/estimate/_standardize.py
- smash/core/simulation/estimate/_tools.py
- smash/core/simulation/estimate/estimate.py
- smash/core/simulation/optimize/optimize.py
- smash/core/simulation/options.py
- smash/core/simulation/run/run.py
- smash/factory/mesh/mesh.py
- smash/factory/net/net.py
- smash/factory/samples/samples.py
- Enhance API
- Remove default_cost_options method
- Re-factorize standardize event_seg and jreg_cmpt
> ENC: Complete parameters/returns docstring for API

- smash/core/simulation/optimize/optimize.py
Fix Issue #76: Add forward run at the end of optimization process with ANN.
> FIX: Update final states when using ANN mapping for regionalization

- doc/source/developers_guide/index.rst
- smash/_constant.py
- smash/core/signal_analysis/metrics/metrics.py
- smash/core/signal_analysis/prcp_indices/prcp_indices.py
- smash/core/signal_analysis/segmentation/segmentation.py
- smash/core/signal_analysis/signatures/signatures.py
- smash/core/simulation/_standardize.py
- smash/core/simulation/optimize/optimize.py
- smash/core/simulation/options.py
- smash/factory/net/net.py
- smash/tests/core/simulation/test_run.py
DOC:
- Finish API Signal Analysis documentation
- Add documentation for default_optimize_options
CODE:
- Enhance early_stopping argument to be able to stop training from the total number of epochs
- Fix last iteration of training (do not update weights and re-run a forward propagation with net net._predict() for all cells)
> ENC/FIX: Enhance API doc and fix early_stopping for ann optimize

- f90wrap_utils/finalize_f90wrap.py
Replace the f90wrap \_\_str\_\_ method by a \_\_repr\_\_ that loop on all attributes and only print accessible values. 
Allows to print mesh, input_data etc even if some variables are not allocated !
> ENC: Add f90wrap monkey patch on __str__ method

- README.md
- doc/source/conf.py
- doc/source/developers_guide/index.rst
- doc/source/getting_started/index.rst
- doc/source/release/0.4.1-notes.rst
- doc/source/release/0.5.0-notes.rst
- smash/core/simulation/options.py
- Correct github link
- Minor fix ann optimize display (following the recent fix on projected gradient of ann)
> FIX: correct github link following the change of organization name

- smash/core/model/model.py
- smash/core/signal_analysis/metrics/metrics.py
- smash/core/simulation/control.py
- smash/core/simulation/estimate/estimate.py
- smash/core/simulation/optimize/optimize.py
- smash/core/simulation/run/run.py
- smash/factory/samples/samples.py
- Enhance API doc: minor fixes of docstring, complete doc for the whole simulation section, add doc for several methods in model.py
- TODO: Only several methods in model.py to be finished: 
- setup and mesh
- get/set mu/sigma parameters of Bayes optimization
> ENC: enhance API documentation

- README.md
Add corporate logo to README.md
> MAINT: Update README.md

- smash/core/model/model.py
Print each attribute of Model with a list of sub attributes (max 4)
> ENC: Add repr method to Model

- doc/source/api_reference/principal_methods/simulation.rst
- smash/core/model/model.py
- smash/core/simulation/_doc.py
- smash/core/simulation/control.py
- smash/core/simulation/optimize/optimize.py
- smash/core/simulation/options.py
- smash/core/simulation/run/run.py
Add docstring to control information methods and quick fix on control deallocation
> Doc optimize control info

- smash/core/model/_read_input_data.py
- smash/core/signal_analysis/metrics/metrics.py
- smash/core/signal_analysis/prcp_indices/prcp_indices.py
- smash/core/signal_analysis/segmentation/segmentation.py
- smash/core/signal_analysis/signatures/signatures.py
Update docstring for:
- hydrograph_segmentation
- signatures
- precipitation_indices
- metrics
> DOC: Update docstrings for signal analysis methods

- smash/core/model/_read_input_data.py
- smash/core/model/model.py
- smash/factory/dataset/dataset.py
- smash/factory/mesh/mesh.py
- smash/factory/samples/samples.py
Update docstring for:
- load_dataset
- generate_mesh
- generate_samples
> DOC: Update docstrings for factory sub-package

- doc/source/api_reference/sub-packages/io.rst
- smash/core/model/_read_input_data.py
- smash/io/mesh.py
- smash/io/model.py
- smash/io/model_ddt.py
- smash/io/setup.py
Update docstring for:
- save_setup
- read_setup
- save_mesh
- read_mesh
- save_model_ddt
- read_model_ddt
- save_model
- read_model
> DOC: Update docstrings for io sub-package

- smash/core/model/_read_input_data.py
- smash/core/simulation/_doc.py
- smash/core/simulation/estimate/estimate.py
- smash/core/simulation/optimize/optimize.py
- smash/core/simulation/run/run.py
Update docstring for:
- ForwardRun
- Optimize
- BayesianOptimize
- MultisetEstimate
> DOC: Update docstrings for simulation returned object

- smash/_constant.py
- smash/core/model/_read_input_data.py
- smash/core/simulation/_standardize.py
- Raise Error if descriptors are not found for regionalization mappings
- Move uniform checking on descriptors to read_input_data
> FIX: fix error message for missing descriptors and checking uniform descriptors

- smash/io/model_ddt.py
Fix API doc for model_ddt methods.
> FIX: minor fix doc api model_ddt

- .github/workflows/code-checks.yml
- .github/workflows/doc.yml
- .github/workflows/unit-tests.yml
actions/checkout@v3 -> actions/checkout@v4
actions/setup-python@v4 -> actions/setup-python@v5
> MAINT: Update github actions to use Node.js 20

- doc/source/release/1.0.0-notes.rst
- smash/core/model/model.py
- smash/core/simulation/optimize/optimize.py
- smash/factory/net/_loss.py
- Fix error in loss function for ANN optimization on initial states
- Add early stopping and multicriteria optimization to release note
> FIX/ENH: fix error in ann optim for initial state + enhance release note

- doc/source/user_guide/quickstart/lez_split_sample_test.rst
> DOC: Fix user guide typo

- environment-dev.yml
- pyproject.toml
- requirements-dev.txt
- Add a temporary upper bound to avoid building with f90wrap v0.2.14
- No issue using f90wrap v0.2.14 at runtime
> MAINT: Handle f90wrap compatibility

- smash/core/simulation/_standardize.py
- smash/io/handler/_hdf5_handler.py
- smash/tests/core/simulation/test_bayesian_optimize.py
- smash/tests/core/simulation/test_optimize.py
Fix some bugs found by the latest version of ruff:
- PLW0133 Missing `raise` statement on exception
- PERF403 Use a dictionary comprehension instead of a for-loop
- PLR1704 Redefining argument with the local name
> FIX: fix code check with some bugs detected by ruff 0.5

- .github/workflows/wheel.yml
- meson.build
- pyproject.toml
Ajout des wheels MacOS et Python 3.12
> MAINT: macos py312 wheels

- README.md
Add pypi badge and minor fix readme.
> DOC: Add pypi badge for smash

- doc/source/contributor_guide/development_process_summary.rst
- Update how to fork
- Remove switching to maintenance branch
- Add linters and formatters as command to run before submitting
> DOC: Update contributor guide summary

- smash/core/model/_read_input_data.py
> FIX: Check descriptor missing valus on active cells

- smash/factory/net/_layers.py
- smash/factory/net/_standardize.py
- smash/factory/net/net.py
> FIX: scaling layer from bounded outputs from activation layer

- doc/source/contributor_guide/development_process_details.rst
> DOC: add note to contributor guide for test-baseline (#283)

- doc/source/release/1.0.2-notes.rst
- doc/source/release/index.rst
> MAINT: v1.0.2 release note

- doc/source/getting_started/index.rst
- Add MacOS and Python3.12 as supported platform and Python version
> DOC: Update getting started installation

- doc/source/getting_started/index.rst
Manage compatibility with pip of OS system
> manage kernel pip

- doc/source/release/1.0.2-notes.rst
> MAINT: Update release note

- smash/core/simulation/_doc.py
- smash/core/simulation/optimize/optimize.py
- smash/factory/mesh/mesh.py
- smash/factory/mesh/mw_mesh.f90
- smash/tests/generate_baseline.py
- Fix the smash baseline by updating ruff version
- Add some corrections/fixes for previous PRs
> FIX: fix baseline and add minor corrections to previous PRs

- smash/core/simulation/optimize/_tools.py
Initialise wjreg before entering in the loop to be sure it will exists.
> Fix: Initialise wjreg 

- smash/core/simulation/optimize/_tools.py
- smash/core/simulation/optimize/optimize.py
Fix: initialise wjreg_fast before return the result
> Fix: initialise wjreg_fast before return the result

- smash/core/signal_analysis/segmentation/_tools.py
- smash/core/signal_analysis/segmentation/segmentation.py
- smash/core/signal_analysis/signatures/signatures.py
- smash/tests/diff_baseline.csv
Add info to segmentation algorithm to check  if double events with multiple peaks are detected.
> ENH: add multiple peaks info to hydrograph segmentation algo

- doc/source/user_guide/classical_uses/classical_calibration_io.rst
- doc/source/user_guide/classical_uses/hydrograph_segmentation.rst
- doc/source/user_guide/classical_uses/large_domain_simulation.rst
- doc/source/user_guide/classical_uses/rainfall_indices.rst
- doc/source/user_guide/classical_uses/regionalization_spatial_validation.rst
- doc/source/user_guide/classical_uses/split_sample_temporal_validation.rst
- doc/source/user_guide/classical_uses/working_with_your_own_data.rst
- doc/source/user_guide/in_depth/control_parameters_manipulation.rst
- doc/source/user_guide/in_depth/lat_long_data.rst
- doc/source/user_guide/in_depth/retrieving_control_parameters.rst
- doc/source/user_guide/index.rst
- doc/source/user_guide/quickstart/input_data_model_initialization.rst
- smash/core/model/model.py
- Change user guide name "user-provided data" to "working with your own data".
- Fix/improve user guide on hydrograph segmentation.
- Fix tutos in classical uses section: split test, large sample, regionalization (removing demo data loading)
- Remove lat long guide (that will be added in the section "working with your own data").
> DOC: change of user guide order/title and fix tutos in classical uses section

- doc/source/user_guide/external_tools/sensitivity_analysis.rst
Add content to doc/source/user_guide/external_tools/sensitivity_analysis.rst
> DOC: external tool - sensitivity analysis

- doc/source/conf.py
Pas grand chose mais ca me faisait de l'oeil quand j'ouvrais la documentation ;)
> DOC: Dynamic copyright year

- generate_version.py
- smash/core/model/_read_input_data.py
- smash/core/model/_standardize.py
- smash/core/model/model.py
- smash/core/simulation/optimize/optimize.py
- smash/core/simulation/run/_standardize.py
- smash/factory/mesh/_tools.py
- smash/factory/net/net.py
- smash/tests/core/simulation/test_bayesian_optimize.py
- smash/tests/core/simulation/test_estimate.py
- smash/tests/core/simulation/test_optimize.py
- smash/tests/core/simulation/test_run.py
- smash/tests/core/test_read_input_data.py
- smash/tests/factory/test_net.py
- smash/tests/io/test_model_io.py
New version of ruff has been released, need to update the code with this version.
> MAINT: update ruff format with new version

- doc/source/conf.py
- doc/source/getting_started/index.rst
- pyproject.toml
This PR simplifies future upgrades and changes to the Python version in smash:
- Define an upper Python version in pyproject.toml
- Reordering classifiers for better visibility
- Add dynamic variables in the configuration documentation
> ENH: Dynamic variables for Python versions in documentation

- doc/source/user_guide/files_with_code_block.csv
- doc/source/user_guide/in_depth/retrieving_control_parameters.rst
Add tutorial for retrieving control parameters and continuous calibration.
> DOC: add user guide retrieving control

- doc/source/_static/css/smash.css
Remove This Page header doc smash
> MAINT/FIX: remove This Page header doc smash (#419)

- doc/source/_static/bib/references.bib
- doc/source/math_num_documentation/index.rst
- doc/source/math_num_documentation/optimization_algorithms.rst
- doc/source/user_guide/classical_uses/regionalization_spatial_validation.rst
- doc/source/user_guide/classical_uses/split_sample_temporal_validation.rst
- doc/source/user_guide/quickstart/forward_run_classical_calibration.rst
- smash/_constant.py
- smash/core/simulation/_doc.py
- smash/core/simulation/_standardize.py
- smash/core/simulation/optimize/_standardize.py
- smash/core/simulation/optimize/optimize.py
- smash/fcore/derived_type/mwd_optimize_options.f90
- smash/tests/core/simulation/test_optimize.py
* ENH: Add gradient-free optimizers (nelder-mead and powell)
* Update doc/source/user_guide/classical_uses/split_sample_temporal_validation.rst
* Apply suggestions from code review
> ENH: Add gradient-free optimizers (nelder-mead and powell) (#425)

- CITATIONS.rst
- doc/source/release/1.1.1-notes.rst
- doc/source/release/index.rst
- smash.bib
- Patch release notes v1.1.1
- Added related-smash reference (Evin et al., 2024)
> Prepare for patch release v1.1.1

- doc/source/api_reference/principal_methods/model.rst
- smash/core/model/_build_model.py
- smash/core/model/model.py
Backporting PR #432 by @maximejay.
> The interception reservoir capacities can be now calibrated after the model creation (#432) by @maximejay
