DassHydro/smash

doc/source/release/0.5.0-notes.rst, doc/source/user_guide/in_depth/optimize/bayes_optimize.rst, smash/core/simulation/bayes_optimize.py
- Enhancements/Fixes for bayes_optimize:
- remove density attribute in preparation for V1.0.0, which will be integrated by a joint probability
- remove unnecessary numpy copy for optimizing computational memory
- enhance loop of assigning values to distributed map for optimizing computational time
- Fix cost not displayed in user guide Bayesian optimization
- Update release note
=> MAINT/FIX: remove density attribute of BayesResult in preparation for V1.0.0

doc/source/release/0.5.0-notes.rst, smash/mesh/mw_meshing.f90
This commit should fix a segmentation fault when two neighboring cells have antagonistic flow directions.
See issue #31
=> FIX: Fix smash.generate_mesh segmentation fault

doc/source/math_num_documentation/signal_analysis/hydrograph_segmentation.rst, doc/source/release/0.5.0-notes.rst, smash/core/_event_segmentation.py, smash/core/model.py
Fix segmentation algorithm:
- If multiple events are detected, the duration of the merged event is no longer constrained by the max duration parameter. Instead, its duration may exceed this value.
=> FIX: max_duration event segmentation algorithm

doc/source/release/0.5.0-notes.rst, smash/core/_build_model.py
=> Fix start time equal end time

doc/source/api_reference/hdf5_handler.rst, doc/source/api_reference/hdf5_io.rst, doc/source/api_reference/object_handler.rst, doc/source/release/0.5.1-notes.rst, doc/source/release/index.rst, smash/core/_constant.py, smash/core/simulation/_standardize.py, smash/tests/core/test_constant.py
=> Fix missing ci missing api doc

doc/source/release/0.5.1-notes.rst, smash/io/mesh_io.py, smash/tools/hdf5_handler.py
- Fix bug on saving mesh
- Fix minor bug on hdf5_handler:
```python3
keys_data = smash.tools.object_handler.generate_object_structure(instance)
```
smash was not previously imported!
- Update release notes.
=> Fix some bugs in smash.io

smash/core/model/model.py
Make deepcopy for optimize_options, cost_options and common_options.
TODO: Do the same for return_options
=> FIX: make a deepcopy for _options parameters in Model

smash/core/model/_standardize.py, smash/factory/mesh/mw_mesh.f90
This PR fixes two 0.5.0 bugs
- Flow distance bug on adjacent non-nested catchments
- Error message when end_time argument equal to start_time argument
=> Fix bug flwdst time

smash/_constant.py, smash/core/model/model.py, smash/core/simulation/_standardize.py, smash/core/simulation/estimate/_tools.py, smash/core/simulation/estimate/estimate.py, smash/core/simulation/optimize/_standardize.py, smash/core/simulation/optimize/optimize.py, smash/core/simulation/options.py, smash/core/simulation/run/_standardize.py, smash/core/simulation/run/run.py
Remove cost_variant parameter from simulation functions in Python.
=> MAINT: Remove cost_variant from model simulation Python interface

smash/_constant.py, smash/core/model/_build_model.py, smash/core/model/_standardize.py, smash/fcore/derived_type/mwd_setup.f90, smash/fcore/routine/mw_interception_capacity.f90
- Add "adjust_interception" key in SetupDT
- Rename "compute_ci" to "adjust_ci"
- Lower the upper bound of interception capacity values (5 to 3)
=> MAINT: Add key to trigger or not the GR interception capacity adjustment

.gitignore, environment-dev.yml, makefile, requirements-dev.txt
- Add pytest-cov as dev dependency
- Add makefile target test-coverage to run test and coverage report (term and html)
- Update .gitignore
=> ENC: Add coverage to tests with pytest-cov plugin

.gitignore
Update .gitignore file to ignire Fortran wrapping files, Fortran module files, Compiled Object files and auto generated api reference documentation rst files
=> MAINT: Update .gitignore

smash/fcore/external/mwd_bayesian_tools.f90, smash/fcore/forward/forward_db.f90, smash/fcore/operator/md_routing_operator.f90, smash/fcore/optimize/mwd_cost.f90, smash/fcore/routine/mwd_parameters_manipulation.f90
Remove maximum of warnings. A bunch of warnings are still here in forward_db.f90. need to check if we can rewrite the direct model to remove some
=> FIX: Remove Fortran warnings

doc/gen_dataset.py, smash/core/model/model.py, smash/core/signal_analysis/prcp_indices/prcp_indices.py, smash/factory/mesh/_tools.py, smash/factory/mesh/mesh.py, smash/factory/mesh/mw_mesh.f90, smash/factory/net/_layers.py, smash/factory/net/_optimizers.py, smash/factory/samples/samples.py, smash/io/_error.py, smash/tests/core/simulation/test_optimize.py
- Generate a window when delineating catchment. It makes the generation faster when the flow direction file domain is larger than the catchment (mondial flwdir vs french catchment)
- Do not trim zeros but only the mask, we can have 0 in flow direction
- Set huge(0._4) as min_tol in Fortran
=> ENH: Upgrade generate mesh

smash/_constant.py, smash/core/model/_read_input_data.py, smash/core/simulation/_doc.py, smash/core/simulation/_standardize.py
- Switch from error to warning the reading of observed dicharge file
- Switch order of check for end_warmup cost_options. It must be done before gauge
- Switch cost_options element order
- Add a raise Error if there is no observed discharge available at any optimized gauge. Only for optimization, will still run in forward_run
=> FIX: Check that there is available observed discharge at optimized gauge

doc/source/contributor_guide/development_process_details.rst, doc/source/math_num_documentation/hydrological_signature.rst, f90wrap/finalize_f90wrap.py, makefile.dep, smash/_constant.py, smash/core/model/_standardize.py, smash/core/model/model.py, smash/core/simulation/_standardize.py, smash/factory/dataset/dataset.py, smash/fcore/derived_type/md_checkpoint_variable.f90, smash/fcore/derived_type/mwd_mesh.f90, smash/fcore/derived_type/mwd_returns.f90, smash/fcore/derived_type/mwd_setup.f90, smash/fcore/forward/forward_db.f90, smash/fcore/forward/md_simulation.f90, smash/fcore/operator/md_gr_operator.f90, smash/fcore/operator/md_routing_operator.f90, smash/fcore/operator/md_snow_operator.f90, smash/fcore/operator/md_vic3l_operator.f90, smash/fcore/routine/mw_atmos_statistic.f90, smash/fcore/routine/mw_interception_capacity.f90, smash/fcore/routine/mwd_atmos_manipulation.f90, smash/fcore/routine/mwd_sparse_matrix_manipulation.f90, smash/tests/test_constant.py
This commit is an upgrade of the adjoint model allowing time step checkpoints to lower the maximum memory usage. By default, in the forward sweep of the adjoint, at each time, n arrays of shape (nrow, ncol) where pushed. This arrays were poped at the end of the forward sweep which result in some case (large domain and time steps) to a too high memory peak. This commit adds checkpoints in the forward sweep to reduce the memory peak and pass the variables that must be checkpointed at each time (i.e. fluxes and states) to a vector of active cell instead of a grid of number of rows and columns.
This upgrade should be pretty efficient for large domain and time step calibration
=> ENH: Low memory adjoint

smash/core/model/_read_input_data.py
This PR should resolve the issue #144
=> FIX: Fix a bug when the csv file of qobs start or end with start_time or end_time

doc/source/release/1.0.0-notes.rst, smash/core/model/_read_input_data.py
This commits resolves an issue when computing min and max value of a physiographic descriptor when there are missing values that are converted to -99.
It fixes the issue #155
=> FIX: Min Max computation for physiographic descriptor

doc/source/release/1.0.0-notes.rst
- Correct release note on "Error in projected gradient computation with ANN mapping"
- Add release notes "Optimization of initial states with ANN mapping", "Final states not computed when using ANN mapping".
=> FIX/ENH: fix release note on proj G and enhance release note 1.0

doc/source/user_guide/quickstart/cance_first_simulation.rst, doc/source/user_guide/quickstart/france_large_domain_simulation.rst, smash/core/model/model.py, smash/tests/core/test_read_input_data.py
Two notes has been added. One in the Model docstring and one in the Cance User Guide to explain the smash convention on ``start_time`` and ``end_time``. This PR should close #161
=> DOC: Add notes to explain smash dates convention

doc/source/release/1.0.0-notes.rst, smash/fcore/routine/mw_interception_capacity.f90
Missing values were not properly taken into account in the calculation of the interception reservoir. Missing values in Fortran for precipitation and potential evapotranspiration are stored as ``-99``, resulting in erroneous values. This was fixed simply by not incorporating these values into the calculation.
=> FIX: Handle missing values for interception capacity calculation

smash/core/simulation/_standardize.py
This PR would fix the issue arising in the scaling layer of **net** when the keys of **bounds** are not in the same order as **parameters** when the **bounds** argument is specified within the **optimize_options**. This discrepancy occurs because the standardize function for **net** does not appropriately adjust the order of **bounds** according to the order of **parameters**.
=> FIX: parameter order in bounds defined in scaling layer of net

.github/workflows/code-checks.yml, .github/workflows/doc.yml, .github/workflows/unit-tests.yml, doc/source/release/1.0.0-notes.rst, environment-dev.yml, environment.yml, requirements.txt, smash/core/model/_build_model.py, smash/core/model/_read_input_data.py, smash/factory/mesh/_standardize.py, smash/factory/mesh/_tools.py, smash/factory/mesh/mesh.py, smash/tests/test_define_global_vars.py
This commit addresses the problem of distributing smash with gdal. gdal doesn't provide binary wheels directly, so you need to install the gdal library on your system before you can install gdal bindings in Python. One way of working with gdal simply in Python is conda, but in order to facilitate the distribution of smash on different OS (linux, maxos and windows), it is simpler to use rasterio to read raster (rasterio provides a binary wheel directly which include gdal). This change is not neutral and leads to performance losses in terms of raster calculation time (rain, etp, descriptors, etc). Generally speaking, reading the input data is a relatively quick process compared with a calibration. However, if the calculation time for reading becomes too great a concern, it can be …
=> MAINT: Switch from gdal to rasterio

Makefile, smash/tests/generate_baseline.py
Since the switch to meson to build smash. The import things made when generating the baseline did not work anymore.
I also cleaned the collecting step to avoid reading precipitation and potential evapotranspiration for each model structure.
=> FIX: Fix generate baseline

smash/fcore/derived_type/mwd_setup.f90
The maximum length of a path has been adjusted to 256 characters instead of 128
=> Fix directory path max length

doc/source/contributor_guide/development_process_details.rst, environment-dev.yml, pyproject.toml, requirements-dev.txt
- Add lower bounds to several packages in pyproject for the compatibility with numpy 2.0.
- Remove version bounds in requirement.txt and environment-dev.yml (developers are required to update their pip and conda to ensure that they have the latest package versions).
- Add a reminder in contributor guide (detail development process) for pip and conda update before compiling smash.
=> MAINT: update pyproject.toml for compatibility with numpy 2

smash/_constant.py, smash/core/model/_standardize.py, smash/core/simulation/_standardize.py, venv_install.sh
@maximejay
Petite galère qd j'ai voulu changer de branch pour merge ta pull request. Je me suis permis de reprendre tes commits directement depuis main. Tu me dis si c'est ok
=> Rebase of MJA pull request on main

smash/_constant.py, smash/core/model/_standardize.py, smash/core/simulation/_standardize.py, venv_install.sh
=> Rebase of MJA pull request on main (#241)

doc/Makefile, doc/source/_ext/custom_options_directive.py, doc/source/release/0.2.4-notes.rst, doc/source/release/0.3.0-notes.rst, doc/source/release/0.3.1-notes.rst, doc/source/release/0.4.0-notes.rst, doc/source/release/0.4.1-notes.rst, doc/source/release/0.4.2-notes.rst, doc/source/release/0.5.0-notes.rst, doc/source/release/1.0.0-notes.rst, doc/source/release/1.0.1-notes.rst, doc/source/release/template-notes.rst, environment-dev.yml, pyproject.toml, requirements-dev.txt, smash/core/model/model.py, smash/core/signal_analysis/evaluation/evaluation.py, smash/core/signal_analysis/prcp_indices/prcp_indices.py, smash/core/signal_analysis/segmentation/segmentation.py, smash/core/signal_analysis/signatures/signatures.py, smash/core/simulation/_doc.py, smash/core/simulation/estimate/estimate.py, smash/core/simulation/optimize/optimize.py, smash/core/simulation/options.py, smash/core/simulation/run/run.py, smash/factory/samples/samples.py, smash/io/model_ddt.py
- Add Sphinx version disjunction in documentation custom directive (soon deprecated)
- Remove warning "summarized item should not include the current module"
- Add ``--fail-on-warning`` option when building the documentation
=> MAINT: Sphinx v7.4 compatibility

smash/factory/net/_layers.py, smash/factory/net/_standardize.py, smash/factory/net/net.py
Scaling layer is now able to take the outputs from other activation functions (not only sigmoid) such as softmax and tanh.
=> FIX: scaling layer for bounded outputs from activation layer

doc/source/contributor_guide/development_process_summary.rst
Backport of #264 
- Update how to fork
- Remove switching to maintenance branch
- Add linters and formatters as command to run before submitting
=> DOC: Update contributor guide summary

smash/factory/mesh/mw_mesh.f90
Fix crash in generate mesh if a well is present at a cell : infinite recursive loop. Just test if it is a well and cycle.
=> Fix crash in generate mesh if a well is present at a cell

smash/factory/mesh/mw_mesh.f90
=> Fix crash in generate mesh if a well is present at a cell : infinite recursive loop. Just test if it is a well and cycle

doc/source/contributor_guide/development_process_details.rst
Add a note to contributor guide for properly generating the ``diff_baseline.csv`` file.
=> DOC: add note to contributor guide for test-baseline

smash/_constant.py, smash/core/model/_standardize.py, smash/core/simulation/_doc.py, smash/core/simulation/_standardize.py
Backport of #287 
* ENH: Mask active cell when checking if parameter is inside feasible domain
- Allow to pass any value to a non active cell and it does not return an error.
- Ruff and fprettify formatting applied
- Remove unused constant TOL_BOUNDS since F_PRECISION is now used
* FIX: Add F_PRECISION to serr parameters
Missing F_PRECISION for structural error parameters
* FIX PR: Clean model standardize
=> ENH: set parameters condition outside active cell

doc/Makefile
To ensure the datasets are up-to-date with the online version, it's recommended to remove local files before generating the documentation.
=> MAINT: remove also dataset directories when using make doc-clean

smash/core/model/_read_input_data.py
This commit should fix the issue #317
=> FIX: Rounding error with array slice with lat-lon raster

doc/generate_dataset.py, doc/source/api_reference/sub-packages/factory.rst, doc/source/user_guide/quickstart/cance_first_simulation.rst, smash/factory/__init__.py, smash/factory/mesh/_standardize.py, smash/factory/mesh/mesh.py, smash/factory/mesh/mw_mesh.f90, smash/fcore/routine/mw_mask.f90, smash/tests/factory/test_mesh.py
- Add a new fonction `smash.factory.detect_sink` that check for sinks in the flow direction file. It returns an array masking the sinks cells. It can also write a raster file
- Handle warning either for bbox meshing or xy meshing
- Remove sink cells when bbox meshing
- Avoid sink cells when xy meshing
- Fix help for `--tar` argument in `generate_dataset.py`
=> FIX: Update sink detection

smash/fcore/forward/forward_db.f90, smash/fcore/forward/forward_openmp_db.f90, smash/fcore/operator/md_gr_operator.f90, smash/tests/diff_baseline.csv
Fix expressions for ps, es and gr in gr production.
=> MAINT/FIX: fix expressions for ps, es and gr in gr production

environment-dev.yml, pyproject.toml, requirements-dev.txt, smash/factory/mesh/_standardize.py, smash/factory/mesh/_tools.py, smash/factory/mesh/mesh.py, smash/factory/mesh/mw_mesh.f90
- It is now possible to use catchment contour to constrain the allocation of the catchment outlet instead of the catchment area only. The contours are pass from a shapefile with at least a `code` field
- Add geopandas as a new dependency to work with shapefiles
=> ENH: Contour-based meshing with shapefiles

.github/workflows/wheel.yml
Switch to `macOS-13` env as `macOS-12` will be obsolete on 3 December 2024
See https://github.com/actions/runner-images/issues/10721
=> MAINT: Switch to macOS-13 env

smash/core/simulation/_standardize.py
Fix wrong slice size on model.response_data.q when checking availabl discharges before optimize (missing last time-step).
=> Fix wrong slice size on model.response_data.q when checking available discharges

smash/_constant.py, smash/fcore/forward/forward_db.f90, smash/fcore/forward/forward_openmp_db.f90, smash/fcore/operator/md_gr_operator.f90, smash/tests/diff_baseline.csv, smash/tests/test_constant.py
- Remove correction on the coefficient 0.9 and 0.1
- Add correction for Pn in the equation of dh_t/dt
- Fix the calculation of Q_t in ODE and neural ODE structure
- Re-compute the Jaco matrix for new formulation
=> MAINT: Fix flux correction and Jaco calculation for hybrid gr4_ode_mlp structure

doc/source/contributor_guide/development_process_details.rst, doc/source/user_guide/files_with_code_block.csv, doc/source/user_guide/post_processing_external_tools/sensitivity_analysis.rst, doc/source/user_guide/pyexec_rst.py
This PR simplifies and improves the process of generating/verifying code when developers choose to write a tutorial using the hardcoded code block style:
- Add a new Python script that extracts and executes code blocks from an .rst file, then generates or updates the output code in the same file. This ensures that the code in hardcoded blocks runs correctly and that outputs are properly generated.
- Improve the contributor guide by detailing the two possible approaches for writing a user guide.
=> ENH/DOC: add automatic output code block generation, improve contributor guide

.gitignore, doc/Makefile, doc/source/user_guide/classical_uses/regionalization_spatial_validation.rst, doc/source/user_guide/quickstart/forward_run_classical_calibration.rst, doc/source/user_guide/quickstart/hydrological_mesh_construction.rst, doc/source/user_guide/quickstart/model_object_initialization.rst
- Remove generated files (hdf5, yaml,...) directly when running script or compiling the documentation
- Thus, no need to remove them with make doc-clean
- Add savefig in gitignore, so no need to make doc-clean to use git add .
- Minor typo fixes user guide
=> MAINT: directly remove generated files when compiling doc

environment-dev.yml, pyproject.toml, requirements-dev.txt
Remove sphinx-autosummary-accessors from smash dependencies since smash no longer uses this sphinx extension.
=> MAINT: Remove sphinx-autosummary-accessors from smash dependencies

smash/factory/net/_layers.py, smash/factory/net/net.py, smash/fcore/forward/forward_db.f90, smash/fcore/forward/forward_openmp_db.f90, smash/fcore/operator/md_gr_operator.f90, smash/fcore/operator/md_neural_network.f90, smash/tests/core/simulation/test_bayesian_optimize.py, smash/tests/core/simulation/test_estimate.py, smash/tests/core/simulation/test_optimize.py, smash/tests/core/simulation/test_run.py, smash/tests/diff_baseline.csv
NaN gradients are produced when using a neural ODE solver on large datasets. The issue appears to stem from the differentiability of the process-parameterization NN (which must be twice differentiable mathematically) and the structure of the Jacobian matrix in the Fortran code.
This PR resolves the issue, tested on ArcMed and Aude catchments, with the following changes:
- The SiLU activation function (which is twice differentiable) replaces ReLU (non-differentiable at 0) in the process-parameterization NN. Since the initial conditions make the output layers very close to zero, using ReLU leads to issues with differentiability at this point;
- SiLU is also added to the list of activation functions available in the Net subpackage;
- Two vectors are used instead of a matrix for computing the …
=> MAINT/ENH: add SiLU activation function

doc/source/user_guide/in_depth/bayesian_estimation.rst, doc/source/user_guide/in_depth/retrieving_control_parameters.rst, smash/core/simulation/_doc.py, smash/core/simulation/optimize/_tools.py, smash/fcore/cost/md_regularization.f90, smash/fcore/derived_type/mwd_control.f90, smash/fcore/forward/forward_db.f90, smash/fcore/forward/forward_openmp_db.f90, smash/fcore/routine/mwd_parameters_manipulation.f90
The name _bkg (background) applied for control values/upper/lower bounds is changed to _raw for clarification.
=> MAINT: change the name _bkg in control info to _raw

smash/core/simulation/estimate/_tools.py, smash/tests/core/simulation/test_estimate.py, smash/tests/diff_baseline.csv
- This PR corrects the calculation of the Mahalanobis distance in the case of spatially distributed parameters. The previous formulation separated the variance term from the squared difference.
The Mahalanobis distance is now computed as:
$`
\int_{x\in\Omega}\left(\mathrm{Var}\left(\boldsymbol{\theta}^*_\alpha(x)\right)^{-1}\odot \left(\boldsymbol{\theta}^*_\alpha(x)-\boldsymbol{\theta}^{0}(x)\right)\odot\left(\boldsymbol{\theta}^*_\alpha(x)-\boldsymbol{\theta}^0(x)\right)\right) dx
`$
instead of the previous formulation:
$`
\left(\int_{x\in\Omega}\mathrm{Var}\left(\boldsymbol{\theta}^*_\alpha(x)\right)^{-1}dx\right) \odot \left(\int_{x\in\Omega}\left(\boldsymbol{\theta}^*_\alpha(x)-\boldsymbol{\theta}^{0}(x)\right)\odot\left(\boldsymbol{\theta}^*_\alpha(x)-\boldsymbol{\theta}^0(x)\right)d …
=> MAINT/FIX: correct the mahal distance calculation in case of distributed parameters

.github/workflows/wheel.yml, doc/source/getting_started/index.rst
Due to the deprecation of the Windows 2019 Actions runner image (https://github.com/actions/runner-images/issues/12045) and an unresolved issue related to wheel creation on windows-2022 when compiling f90wrap (https://github.com/DassHydro/smash/issues/433), Windows support for smash is temporarily unavailable.
=> MAINT: Temporarily drop windows support

.github/workflows/wheel.yml, doc/source/getting_started/index.rst, f90wrap/generate_f2py-f90wrap.py, smash/fcore/meson.build
Update of Windows wheel building on GitHub actions:
- Switch to Windows 2022 runner
- Patch f2py C file to handle _setjmpex linking error (use setjmp.h instead of setjmpex.h)
=> MAINT: Windows wheel

doc/source/math_num_documentation/mapping.rst, doc/source/user_guide/classical_uses/regionalization_spatial_validation.rst, doc/source/user_guide/in_depth/bayesian_estimation.rst, doc/source/user_guide/in_depth/retrieving_control_parameters.rst, smash/_constant.py, smash/core/simulation/_doc.py, smash/fcore/forward/forward_db.f90, smash/fcore/forward/forward_openmp_db.f90, smash/fcore/routine/mwd_parameters_manipulation.f90, smash/tests/core/simulation/test_optimize.py, smash/tests/diff_baseline.csv
- Mapping name "multi-polynomial" is deprecated and replaced by "multi-power".
- Corresponding changes made for the baseline
=> MAINT: changing mapping name multi-polynomial to multi-power

smash/factory/mesh/_standardize.py, smash/factory/mesh/mesh.py
Salut,
Une nouvelle et petite pull request qui ajoute une option à generate_mesh() permettant d'exclure des exutoires dont la surface modélisé est très différente de la surface réel. Pour cela un seuil est défini: area_error_th. 
L'erreur sur les surface est calculé par (Smodel-Sobs)/Sobs.
Si area_error_th est laissé à None, alors le test n'est pas réalisé et tous les exutoires sont ajoutés comme avant :)
Cette pull request s'ajoute à la pull request Regional_meshing #430.
Cette option est interessante car:
- Si la liste d'exutoire passée à Generate mesh est longue, cela permet de filtrer au besoin les exutoires qui sont ajoutés au mesh, sans avoir à le fair à la main et donc en limitant les calculs aux exutoires/domaine validé (par ex si la surface modélisé est de 5 km2 alors que la …
=> MAINT: Exclude mesh outlets based on surface error
